<html>
<head>
    <meta charset="utf-8">
    <title>main page</title>


</head>

<body>


<script>
    var Ext = Ext || {};
    Ext.theme = {
        name: ""
    };
</script>
<script src="http://cdn.sencha.com/ext/gpl/5.1.0/build/ext-all.js"></script>
<script src="http://cdn.sencha.com/ext/gpl/5.1.0/build/packages/ext-theme-crisp/build/ext-theme-crisp.js"></script>
<link rel="stylesheet" href="http://cdn.sencha.com/ext/gpl/5.1.0/build/packages/ext-theme-crisp/build/resources/ext-theme-crisp-all.css">
<script type="text/javascript" src="js/extjs/UserApp/app.js"></script>
<link rel="stylesheet" href="js/extjs/UserApp/style.css">


<h1>Welcome</h1>
<a href="/user/index/selectname">UsersDataBase</a>
<a href="/user/index/info">Info Page</a>





</body>
</html>
