<html>
<head>
    <meta charset="utf-8">
    <title>Info page</title>


</head>

<body>

<h1>Instruction</h1>
<hr>
<ul>
    <li>Проект на github.com (откроется в новом окне)<a href="https://github.com/sos-zone/Univer.git"  target="_blank">Проект</a></li>
    <li>Main page is <a href="/user">Main page</a></li>
    <li>DataBase page is <a href="/user/index/selectname">UsersDataBase</a></li>
    <li>At top menu user can sort people by Education, City, ID</li>
    <li>To <strong>change</strong> user info or <strong>delete</strong> user click on person card</li>
    <li>To <strong>create</strong> new user press AddUserButton (card's should not be marked (reload page))</li>
</ul>
<hr>

This program was create by Anzhenka Siarhei.<br>
mts: +375 29 856 32 15<br>
Ссылка на резюме: <a href="http://jobs.tut.by/resume/86f98469ff0271b37c0039ed1f594b6c785054"  target="_blank">Резюме</a><br>
email: <a href="mailto:new_word@tut.by">new_word@tut.by</a><br>
<strong>P.S.:</strong> Проект как есть по состоянию на 10.09.2015. Разработал насколько хватило времени... (много времени и сил уделяется основной работе).
Буду рад предложению о работе. Не требовательный. Работа нравится. Желание развиваться есть.






</body>
</html>
