<html>
<head>
    <meta charset="utf-8">
    <title>Info page</title>


</head>

<body>

<h1>Instruction</h1>
<hr>
<ul>
    <li>Проект на github.com<a href="https://github.com/sos-zone/Univer.git"  target="_blank">Ссылка</a></li>
    <li>Main page is <a href="/user">Main page</a></li>
    <li>DataBase page is <a href="/user/index/selectname">UsersDataBase</a></li>
    <li>At top menu user can sort people by Education, City, ID</li>
    <li>To change user info click on user card</li>
    <li>To create new user press AddUserButton</li>
    <li>to delete user click right mouse button on user card and choose submenu "delete"</li>
</ul>
<hr>

This program was create by Anzhenka Siarhei.<br>
mts: +375 29 856 32 15<br>
email: <a href="mailto:new_word@tut.by">new_word@tut.by</a><br>
<strong>P.S.:</strong> Проект как есть по состоянию на 10.09.2015. Разработал насколько хватило времени... (много времени и сил уделяется основной работе).
Буду рад предложению о работе на Ваших условиях. Есть желание развиваться...






</body>
</html>

